In [2]:
import pandas as pd
print("done")

done

In [ ]:
# pandas has 2 core object : series , data frame

0    1
1    2
2    3
3    4
dtype: int64

In [8]:
#series

pd.Series((1,2,3,4),name = "age")

0    1
1    2
2    3
3    4
Name: age, dtype: int64

In [11]:
# dataframe
#dict

di ={"name": ["aryan","mango" ,"ball", "pen"] , 
     "identity":["human","fruit", "sports","stationary"]}

df =pd.DataFrame(di)

In [14]:
print(type(df))

<class 'pandas.DataFrame'>

In [16]:
df.head(2)

    name identity
0  aryan    human
1  mango    fruit

In [18]:
df.tail(2)

   name    identity
2  ball      sports
3   pen  stationary

In [21]:
df.sample(2)

   name    identity
3   pen  stationary
2  ball      sports

In [22]:
df.head()

    name    identity
0  aryan       human
1  mango       fruit
2   ball      sports
3    pen  stationary

In [24]:
type(df["name"])

pandas.Series

In [26]:
df[["name" ,"identity"]]

    name    identity
0  aryan       human
1  mango       fruit
2   ball      sports
3    pen  stationary

In [32]:
#add some col
count=[2,5,1,6]
df.insert(0,"count",count)

In [33]:
df

   count   name    identity
0      2  aryan       human
1      5  mango       fruit
2      1   ball      sports
3      6    pen  stationary

In [ ]:
brand =("god","mazza","vp15" ,"retro")
# df.insert(3,"brand",brand)
df

   count   name    identity  brand
0      2  aryan       human    god
1      5  mango       fruit  mazza
2      1   ball      sports   vp15
3      6    pen  stationary  retro

In [38]:
df["id"] =[1,2,3,4]

In [39]:
df.sample()

   count   name identity brand  id
0      2  aryan    human   god   1

In [48]:
#new df2, id , weight 

df2 = pd.DataFrame({"id":[1,2,3,4,5],"weight":[23,45,67,78,None]})
df2

   id  weight
0   1    23.0
1   2    45.0
2   3    67.0
3   4    78.0
4   5     NaN

In [53]:
#merge or join

pd.merge(df,df2 , how="right",on="id")

   count   name    identity  brand  id  weight
0    2.0  aryan       human    god   1    23.0
1    5.0  mango       fruit  mazza   2    45.0
2    1.0   ball      sports   vp15   3    67.0
3    6.0    pen  stationary  retro   4    78.0
4    NaN    NaN         NaN    NaN   5     NaN